# Generated by Django 3.2.19 on 2023-08-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '__first__'),
        ('practice', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCatalogProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('dosage', models.CharField(blank=True, max_length=1024, null=True)),
                ('frequency', models.CharField(blank=True, max_length=1024, null=True)),
                ('unit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=20, null=True)),
                ('instruction', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('tax_value', models.FloatField(blank=True, null=True)),
                ('discount_value', models.FloatField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=1024, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff')),
                ('drug_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.drugtype')),
                ('drug_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.drugunit')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('offers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practiceoffers')),
                ('taxes', models.ManyToManyField(blank=True, to='practice.Taxes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedureCatalogProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=20, null=True)),
                ('unit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('default_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('tax_value', models.FloatField(blank=True, null=True)),
                ('discount_value', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff')),
                ('offers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practiceoffers')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.procedurecatalog')),
                ('taxes', models.ManyToManyField(blank=True, to='practice.Taxes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProformaInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('cost', models.FloatField(blank=True, default=0, null=True)),
                ('discount', models.FloatField(blank=True, default=0, null=True)),
                ('taxes', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, default='Invoice', max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=512, null=True)),
                ('courier_charge', models.FloatField(blank=True, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=512, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=512, null=True)),
                ('tracking_bill', models.CharField(blank=True, max_length=512, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=4000, null=True)),
                ('delivery_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('cancel_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ManyToManyField(blank=True, to='billing.InventoryCatalogProforma')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice')),
                ('prescription', models.ManyToManyField(blank=True, to='patients.PatientPrescriptions')),
                ('procedure', models.ManyToManyField(blank=True, to='billing.ProcedureCatalogProforma')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
