# Generated by Django 3.2.19 on 2023-08-03 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppBlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=524, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppDiseaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=524, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=524, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('silder_image', models.ImageField(blank=True, null=True, upload_to='android/slider')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=524, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('testimonial_image', models.ImageField(blank=True, null=True, upload_to='android/testimonial')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppYoutubeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=524, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppYoutube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('urllink', models.CharField(blank=True, max_length=524, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appyoutubecategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='android_user.appyoutubecategory')),
            ],
        ),
        migrations.CreateModel(
            name='AppDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
                ('recommended', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='android/disease')),
                ('is_active', models.BooleanField(default=True)),
                ('appdiseasecategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='android_user.appdiseasecategory')),
            ],
        ),
        migrations.CreateModel(
            name='AppBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=14, null=True)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='android/blog')),
                ('is_active', models.BooleanField(default=True)),
                ('appblogcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='android_user.appblogcategory')),
            ],
        ),
    ]
