# Generated by Django 3.2.19 on 2023-08-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '__first__'),
        ('patients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('block_from', models.DateTimeField(blank=True, null=True)),
                ('block_to', models.DateTimeField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=512, null=True)),
                ('allow_booking', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('notify_via_sms', models.BooleanField(default=True)),
                ('notify_via_email', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=512, null=True)),
                ('cancel_by', models.CharField(blank=True, max_length=512, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('schedule_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_till', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Scheduled', 'SCHEDULED'), ('Waiting', 'WAITING'), ('Engaged', 'ENGAGED'), ('Check Out', 'CHECKOUT'), ('Cancelled', 'CANCELLED'), ('No Show', 'NO SHOW')], default='Scheduled', max_length=64)),
                ('waiting', models.DateTimeField(blank=True, null=True)),
                ('engaged', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.appointmentcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patientprocedure')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
