# Generated by Django 3.2.19 on 2023-08-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('patients', '0004_alter_generatedpdf_uuid'),
        ('accounts', '0001_initial'),
        ('mlm', '0001_initial'),
        ('muster_roll', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='bedbookingpackage',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='bedbookingpackage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.roomtypesettings'),
        ),
        migrations.AddField(
            model_name='bedbookingpackage',
            name='state_taxes',
            field=models.ManyToManyField(blank=True, related_name='bed_other_state_tax', to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='bedbookingpackage',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='bed_normal_tax', to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='communications',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='diagnoses',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='drugcatalog',
            name='drug_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.drugtype'),
        ),
        migrations.AddField(
            model_name='drugcatalog',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='drugcatalog',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.drugunit'),
        ),
        migrations.AddField(
            model_name='drugcatalogtemplate',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='drugtype',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='drugunit',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='emailcommunications',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.expensetype'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.paymentmodes'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.vendor'),
        ),
        migrations.AddField(
            model_name='expensetype',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='filetags',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='investigations',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='labpanel',
            name='margin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mlm.productmargin'),
        ),
        migrations.AddField(
            model_name='labpanel',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='labpanel',
            name='tests',
            field=models.ManyToManyField(blank=True, to='practice.LabTestCatalog'),
        ),
        migrations.AddField(
            model_name='labtestcatalog',
            name='margin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mlm.productmargin'),
        ),
        migrations.AddField(
            model_name='labtestcatalog',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='medication',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='medicinebookingpackage',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='medicinebookingpackage',
            name='state_taxes',
            field=models.ManyToManyField(blank=True, related_name='medicine_other_state_tax', to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='medicinebookingpackage',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='medicine_normal_tax', to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='medicinebookingpackage',
            name='under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='practice.medicinebookingpackage'),
        ),
        migrations.AddField(
            model_name='observations',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='otherdiseases',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='practice.Permissions'),
        ),
        migrations.AddField(
            model_name='practice',
            name='reg_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.city'),
        ),
        migrations.AddField(
            model_name='practice',
            name='reg_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.country'),
        ),
        migrations.AddField(
            model_name='practice',
            name='reg_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.state'),
        ),
        migrations.AddField(
            model_name='practicecalendersettings',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='practicecomplaints',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='practiceoffers',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='practiceprintsettings',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='practicereferer',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='practicestaff',
            name='advisors',
            field=models.ManyToManyField(blank=True, to='patients.Patients'),
        ),
        migrations.AddField(
            model_name='practicestaff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department', to='muster_roll.hrsettings'),
        ),
        migrations.AddField(
            model_name='practicestaff',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designation', to='muster_roll.hrsettings'),
        ),
        migrations.AddField(
            model_name='practicestaff',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='_practice_practicestaff_employees_+', to='practice.PracticeStaff'),
        ),
        migrations.AddField(
            model_name='practicestaff',
            name='role',
            field=models.ManyToManyField(blank=True, to='accounts.Role'),
        ),
        migrations.AddField(
            model_name='practicestaffrelation',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='practicestaffrelation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='practiceuserpermissions',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='practiceuserpermissions',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='practicevitalsign',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='advice_data',
            field=models.ManyToManyField(blank=True, to='practice.Advice'),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='drugs',
            field=models.ManyToManyField(blank=True, to='practice.DrugCatalogTemplate'),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='labs',
            field=models.ManyToManyField(blank=True, to='practice.LabTestCatalog'),
        ),
        migrations.AddField(
            model_name='prescriptiontemplate',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='state_taxes',
            field=models.ManyToManyField(blank=True, related_name='procedure_other_state_tax', to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='procedure_normal_tax', to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='under',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent', to='practice.procedurecatalog'),
        ),
        migrations.AddField(
            model_name='pushnotifications',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='roomtypesettings',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='taxes',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='treatmentnotes',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='visitingtime',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='visitingtime',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
    ]
