# Generated by Django 3.2.19 on 2023-08-03 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        ('patients', '0002_alter_generatedpdf_uuid'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin', to='practice.PracticeStaff'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='staff', to='practice.PracticeStaff'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='patients',
            field=models.ManyToManyField(blank=True, to='patients.Patients'),
        ),
        migrations.AddField(
            model_name='meetingchat',
            name='joinee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meeting.meetingjoinee'),
        ),
        migrations.AddField(
            model_name='meetingjoinee',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='meetingjoinee',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='meetingjoinee',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_user', to='practice.practicestaff'),
        ),
    ]
