# Generated by Django 3.2.19 on 2023-08-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedpdf',
            name='uuid',
            field=models.CharField(default='8a337c35', max_length=40),
        ),
    ]
