# Generated by Django 3.2.19 on 2023-08-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muster_roll', '0001_initial'),
        ('practice', '0001_initial'),
        ('meeting', '0002_auto_20230803_0846'),
        ('mlm', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0002_alter_generatedpdf_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorbank',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='calculatemlm',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patientinvoices'),
        ),
        migrations.AddField(
            model_name='calculatemlm',
            name='margin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mlm.productmargin'),
        ),
        migrations.AddField(
            model_name='coldcalling',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.city'),
        ),
        migrations.AddField(
            model_name='coldcalling',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.country'),
        ),
        migrations.AddField(
            model_name='coldcalling',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.state'),
        ),
        migrations.AddField(
            model_name='inventorycataloginvoice',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='inventorycataloginvoice',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorycataloginvoice',
            name='offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practiceoffers'),
        ),
        migrations.AddField(
            model_name='inventorycataloginvoice',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockentryitem'),
        ),
        migrations.AddField(
            model_name='inventorycataloginvoice',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='inventorycatalogreturn',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='inventorycatalogreturn',
            name='drug_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.drugtype'),
        ),
        migrations.AddField(
            model_name='inventorycatalogreturn',
            name='drug_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.drugunit'),
        ),
        migrations.AddField(
            model_name='inventorycatalogreturn',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorycatalogreturn',
            name='inventory_inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.inventorycataloginvoice'),
        ),
        migrations.AddField(
            model_name='inventorycatalogreturn',
            name='offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practiceoffers'),
        ),
        migrations.AddField(
            model_name='inventorycatalogreturn',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockentryitem'),
        ),
        migrations.AddField(
            model_name='inventorycatalogreturn',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patientinvoices'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='medicalcertificate',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='medicinebooking',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.medicinebookingpackage'),
        ),
        migrations.AddField(
            model_name='medicinebooking',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='patientallopathicmedicines',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientcallnotes',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='patientcallnotes',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientcallnotes',
            name='practice_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patientclinicnotes',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patientclinicnotes',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientclinicnotes',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='file_tags',
            field=models.ManyToManyField(blank=True, to='practice.Filetags'),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientgroups',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientinventory',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='patientinvoices',
            name='inventory',
            field=models.ManyToManyField(blank=True, to='patients.InventoryCatalogInvoice'),
        ),
        migrations.AddField(
            model_name='patientinvoices',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientinvoices',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientinvoices',
            name='prescription',
            field=models.ManyToManyField(blank=True, to='patients.PatientPrescriptions'),
        ),
        migrations.AddField(
            model_name='patientinvoices',
            name='procedure',
            field=models.ManyToManyField(blank=True, to='patients.ProcedureCatalogInvoice'),
        ),
        migrations.AddField(
            model_name='patientinvoices',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.reservations'),
        ),
        migrations.AddField(
            model_name='patientinvoices',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientmembership',
            name='medical_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.membership'),
        ),
        migrations.AddField(
            model_name='patientmembership',
            name='membership_benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benefit_member', to='patients.patientpayment'),
        ),
        migrations.AddField(
            model_name='patientmembership',
            name='membership_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patientinvoices'),
        ),
        migrations.AddField(
            model_name='patientmembership',
            name='membership_payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_member', to='patients.patientpayment'),
        ),
        migrations.AddField(
            model_name='patientmembership',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientmembership',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientmembership',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patientnotes',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientnotes',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientnotes',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='invoices',
            field=models.ManyToManyField(blank=True, to='patients.InvoiceDetails'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.paymentmodes'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='return_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.returnpayment'),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patientprescriptions',
            name='advice_data',
            field=models.ManyToManyField(blank=True, to='patients.PatientAdvice'),
        ),
        migrations.AddField(
            model_name='patientprescriptions',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patientprescriptions',
            name='drugs',
            field=models.ManyToManyField(blank=True, to='patients.PatientInventory'),
        ),
        migrations.AddField(
            model_name='patientprescriptions',
            name='labs',
            field=models.ManyToManyField(blank=True, to='practice.LabTestCatalog'),
        ),
        migrations.AddField(
            model_name='patientprescriptions',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientprescriptions',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientprocedure',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.registration'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='registration_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patientinvoices'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='registration_payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patientpayment'),
        ),
        migrations.AddField(
            model_name='patientregistration',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patients',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.city'),
        ),
        migrations.AddField(
            model_name='patients',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.country'),
        ),
        migrations.AddField(
            model_name='patients',
            name='dead_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dead_by', to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patients',
            name='follow_up_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followup_staff', to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patients',
            name='medical_history',
            field=models.ManyToManyField(blank=True, to='patients.PatientMedicalHistory'),
        ),
        migrations.AddField(
            model_name='patients',
            name='patient_group',
            field=models.ManyToManyField(blank=True, to='patients.PatientGroups'),
        ),
        migrations.AddField(
            model_name='patients',
            name='pd_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patients',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advisor_practice', to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patients',
            name='practices',
            field=models.ManyToManyField(blank=True, to='patients.PersonalDoctorsPractice'),
        ),
        migrations.AddField(
            model_name='patients',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='religion', to='muster_roll.hrsettings'),
        ),
        migrations.AddField(
            model_name='patients',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mlm.agentrole'),
        ),
        migrations.AddField(
            model_name='patients',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.state'),
        ),
        migrations.AddField(
            model_name='patientspromocode',
            name='patients',
            field=models.ManyToManyField(blank=True, to='patients.Patients'),
        ),
        migrations.AddField(
            model_name='patientspromocode',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patienttreatmentplans',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.procedurecatalog'),
        ),
        migrations.AddField(
            model_name='patientvitalsigns',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='patientvitalsigns',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientvitalsigns',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientwalletledger',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patientinvoices'),
        ),
        migrations.AddField(
            model_name='patientwalletledger',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='patientwalletledger',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patientpayment'),
        ),
        migrations.AddField(
            model_name='patientwalletledger',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='patientwalletledger',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='personaldoctorspractice',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='procedurecataloginvoice',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='procedurecataloginvoice',
            name='offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practiceoffers'),
        ),
        migrations.AddField(
            model_name='procedurecataloginvoice',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.procedurecatalog'),
        ),
        migrations.AddField(
            model_name='procedurecataloginvoice',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='procedurecatalogreturn',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AddField(
            model_name='procedurecatalogreturn',
            name='offers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practiceoffers'),
        ),
        migrations.AddField(
            model_name='procedurecatalogreturn',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.procedurecatalog'),
        ),
        migrations.AddField(
            model_name='procedurecatalogreturn',
            name='procedure_inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.procedurecataloginvoice'),
        ),
        migrations.AddField(
            model_name='procedurecatalogreturn',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='requestotp',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='requestotp',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='bed_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.bedbookingpackage'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='medicines',
            field=models.ManyToManyField(blank=True, to='patients.MedicineBooking'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='other_diseases',
            field=models.ManyToManyField(blank=True, to='practice.OtherDiseases'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='practice.Taxes'),
        ),
        migrations.AddField(
            model_name='returnpayment',
            name='inventory',
            field=models.ManyToManyField(blank=True, to='patients.InventoryCatalogReturn'),
        ),
        migrations.AddField(
            model_name='returnpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patientinvoices'),
        ),
        migrations.AddField(
            model_name='returnpayment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.patients'),
        ),
        migrations.AddField(
            model_name='returnpayment',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practice'),
        ),
        migrations.AddField(
            model_name='returnpayment',
            name='procedure',
            field=models.ManyToManyField(blank=True, to='patients.ProcedureCatalogReturn'),
        ),
        migrations.AddField(
            model_name='returnpayment',
            name='return_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.paymentmodes'),
        ),
        migrations.AddField(
            model_name='returnpayment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='practice.practicestaff'),
        ),
        migrations.AlterField(
            model_name='generatedpdf',
            name='uuid',
            field=models.CharField(default='02e9f3b8', max_length=40),
        ),
    ]
