# Generated by Django 3.2.19 on 2023-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20230803_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedpdf',
            name='uuid',
            field=models.CharField(default='343a5917', max_length=40),
        ),
    ]
